CLEAR COLUMNS
CLEAR BREAKS
CLEAR COMPUTES

SET LINESIZE 250
SET PAGESIZE 100
SET AUTOCOMMIT ON
SET SERVEROUTPUT ON
SET FEEDBACK ON
SET VERIFY OFF
SET ECHO OFF
SET HEADING ON
SET TAB OFF
SET TERMOUT ON
SET TRIMSPOOL ON
SET TRIMOUT ON
SET TIMING ON
SET LONG 5000
SET LONGCHUNKSIZE 5000
SET NUMWIDTH 10

COLUMN TNAME FORMAT A30
COLUMN TABTYPE FORMAT A15
COLUMN CLUSTERID FORMAT 999999

COLUMN USERNAME FORMAT A25
COLUMN ACCOUNT_STATUS FORMAT A20
COLUMN TABLE_NAME FORMAT A30
COLUMN OBJECT_NAME FORMAT A35
COLUMN OBJECT_TYPE FORMAT A20

COLUMN ID FORMAT 999999
COLUMN EMP_ID FORMAT 999999
COLUMN DEPT_ID FORMAT 999999
COLUMN DOCTOR_ID FORMAT 999999
COLUMN PATIENT_ID FORMAT 999999
COLUMN APPOINTMENT_ID FORMAT 999999
COLUMN ROOM_ID FORMAT 999999
COLUMN BILL_ID FORMAT 999999

COLUMN NAME FORMAT A25
COLUMN FIRST_NAME FORMAT A20
COLUMN LAST_NAME FORMAT A20
COLUMN FULL_NAME FORMAT A30
COLUMN EMP_NAME FORMAT A25
COLUMN DEPT_NAME FORMAT A25
COLUMN PATIENT_NAME FORMAT A25
COLUMN DOCTOR_NAME FORMAT A25

COLUMN SPECIALIZATION FORMAT A25
COLUMN DESIGNATION FORMAT A25
COLUMN ADDRESS FORMAT A35
COLUMN LOCATION FORMAT A25
COLUMN CITY FORMAT A20
COLUMN STATE FORMAT A20
COLUMN COUNTRY FORMAT A20

COLUMN PHONE FORMAT A15
COLUMN MOBILE FORMAT A15
COLUMN EMAIL FORMAT A35

COLUMN SALARY FORMAT 999999999
COLUMN FEES FORMAT 999999999
COLUMN AMOUNT FORMAT 999999999
COLUMN PRICE FORMAT 999999999

COLUMN STATUS FORMAT A15
COLUMN GENDER FORMAT A10
COLUMN BLOOD_GROUP FORMAT A10

COLUMN AVAILABLE_DAYS FORMAT A25
COLUMN DESCRIPTION FORMAT A40

COLUMN CREATED_AT FORMAT A20
COLUMN UPDATED_AT FORMAT A20
COLUMN DOB FORMAT A20
COLUMN APPOINTMENT_DATE FORMAT A25
COLUMN JOIN_DATE FORMAT A20

ALTER SESSION SET NLS_DATE_FORMAT='DD-MON-YY';

COLUMN APPT_ID FORMAT 9999
COLUMN PATIENT_NAME FORMAT A25
COLUMN DOCTOR_NAME FORMAT A25
COLUMN DEPT_NAME FORMAT A20
COLUMN APPT_DATE FORMAT A12
COLUMN APPT_TIME FORMAT A12
COLUMN STATUS FORMAT A15
COLUMN REASON FORMAT A35
